apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apiservice-cdn.yaml
  - apiservice-wardle.yaml
  - auth-delegator.yaml
  - deployment.yaml
  - ns.yaml
  - pvc.yaml
  - rbac-bind.yaml
  - rbac.yaml
  - sa.yaml
  - service.yaml

namespace: toms-place
